[theme]

base = "dark"

# Primary accent color. (Elementos interactivos)
primaryColor = "#254441"

# Background color of the app. (fondo de la página)
backgroundColor = "#FF6F59"

# Background color used for most interactive widgets. (color de la barra lateral)
secondaryBackgroundColor = "#43AA8B"

# Color used for almost all text. (color de texto)
textColor = "#000000"

# This can be one of the following: (tipografías)
# - "sans-serif"
# - "serif"
# - "monospace"
font = "sans-serif"
